DROP TABLE IF EXISTS TIPO_CAMBIO;

CREATE TABLE TIPO_CAMBIO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  valor_tipo_cambio NUMERIC NOT NULL,
  moneda_origen VARCHAR(250) NOT NULL,
  moneda_destino VARCHAR(250) NOT NULL
);
